id: federated_learning_workflow
namespace: credit_scoring_002

tasks:
  - id: run_federated_learning
    type: io.kestra.plugin.scripts.python.Script
    docker:
      image: "federated-learning-1" # Specifies your Docker service
    inputFiles:
      federated_learning/main.py: |
        # Your main.py file content directly here
        import os
        import sys
        sys.path.append(os.getcwd())

        from main import main

        if __name__ == '__main__':
            main()
    script: |
      python federated_learning/main.py
    env:
      NUM_INSTITUTIONS: "5"
      NUM_SAMPLES: "1000"
      RANDOM_SEED: "42"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 0 * * *" # Run daily at midnight
